### ISSUE TITLE
Project not compiling

### ISSUE THREAD

**Issue by share9** [dclelland/HOWL#1]
I'm not sure how to fix:

<img width="1149" alt="screen shot 2018-10-24 at 6 00 56 pm" src="https://user-images.githubusercontent.com/37937142/47464351-e7561c00-d7b6-11e8-886d-fc81573ac106.png">

**Comment by dclelland** [comment]
I'm sorry man, this project is unfortunately completely unmaintained at present. 😞

**Comment by dclelland** [comment]
Have updated to Swift 5; project should build in Xcode 10.3 now. Still fixing a couple of bugs.

**Comment by dclelland** [comment]
Project builds now; have resubmitted to the app store.
